export const resizeHandlerEl = document.querySelector('.resizeHandler')
export const classSelectorEl = document.querySelector('#classSelector')
export const annotatorEl = document.querySelector('.annotator')
export const mainEl = document.querySelector('main')
export const coordinateIndex = document.querySelector('.coordinateIndex')
